// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.1
// source: chairs.proto

package grpc_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChairRequest) Reset() {
	*x = ChairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chairs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChairRequest) ProtoMessage() {}

func (x *ChairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chairs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChairRequest.ProtoReflect.Descriptor instead.
func (*ChairRequest) Descriptor() ([]byte, []int) {
	return file_chairs_proto_rawDescGZIP(), []int{0}
}

func (x *ChairRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chair *Chair `protobuf:"bytes,1,opt,name=chair,proto3" json:"chair,omitempty"`
}

func (x *ChairResponse) Reset() {
	*x = ChairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chairs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChairResponse) ProtoMessage() {}

func (x *ChairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chairs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChairResponse.ProtoReflect.Descriptor instead.
func (*ChairResponse) Descriptor() ([]byte, []int) {
	return file_chairs_proto_rawDescGZIP(), []int{1}
}

func (x *ChairResponse) GetChair() *Chair {
	if x != nil {
		return x.Chair
	}
	return nil
}

type Chair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Chair) Reset() {
	*x = Chair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chairs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chair) ProtoMessage() {}

func (x *Chair) ProtoReflect() protoreflect.Message {
	mi := &file_chairs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chair.ProtoReflect.Descriptor instead.
func (*Chair) Descriptor() ([]byte, []int) {
	return file_chairs_proto_rawDescGZIP(), []int{2}
}

func (x *Chair) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_chairs_proto protoreflect.FileDescriptor

var file_chairs_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x68, 0x61, 0x69, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22,
	0x0a, 0x0c, 0x43, 0x68, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x72, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69,
	0x72, 0x22, 0x1b, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x31,
	0x0a, 0x0c, 0x43, 0x68, 0x61, 0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x72, 0x12, 0x0d, 0x2e, 0x43, 0x68, 0x61,
	0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x43, 0x68, 0x61, 0x69,
	0x72, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chairs_proto_rawDescOnce sync.Once
	file_chairs_proto_rawDescData = file_chairs_proto_rawDesc
)

func file_chairs_proto_rawDescGZIP() []byte {
	file_chairs_proto_rawDescOnce.Do(func() {
		file_chairs_proto_rawDescData = protoimpl.X.CompressGZIP(file_chairs_proto_rawDescData)
	})
	return file_chairs_proto_rawDescData
}

var file_chairs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chairs_proto_goTypes = []interface{}{
	(*ChairRequest)(nil),  // 0: ChairRequest
	(*ChairResponse)(nil), // 1: ChairResponse
	(*Chair)(nil),         // 2: Chair
}
var file_chairs_proto_depIdxs = []int32{
	2, // 0: ChairResponse.chair:type_name -> Chair
	0, // 1: ChairService.GetChair:input_type -> ChairRequest
	2, // 2: ChairService.GetChair:output_type -> Chair
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chairs_proto_init() }
func file_chairs_proto_init() {
	if File_chairs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chairs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chairs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chairs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chairs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chairs_proto_goTypes,
		DependencyIndexes: file_chairs_proto_depIdxs,
		MessageInfos:      file_chairs_proto_msgTypes,
	}.Build()
	File_chairs_proto = out.File
	file_chairs_proto_rawDesc = nil
	file_chairs_proto_goTypes = nil
	file_chairs_proto_depIdxs = nil
}
